<?php
/**
 * Copyright © 2017 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<span id="result">
    <img class="connecting" hidden="hidden" style="margin:0 5px"
         src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"/>
    <span id="stats_result">
        <?php
        if ($summaryData = $block->getReviewSummary()) {
            foreach ($summaryData as $key => $summary) {
                echo '<span class="fbc-review-summary">';
                if ($summary['status'] == 'success') {
                    echo '<div class="field-summary-rating">';
                    echo '	<div class="rating-box">';
                    echo '		<div class="rating" style="width: ' . (int)$summary['percentage'] . '%;"></span>';
                    echo '	</div>';
                    echo '</div>';
                    echo __(
                        '%1 <br>Rated %2 with <a href="%3" target="_blank">%4 reviews</a>',
                        $block->escapeHtml($summary['name']),
                        $block->escapeHtml($summary['score']) . '/' . (int)$summary['score_max'],
                        $block->escapeUrl($summary['link']),
                        (int)$summary['total_reviews']
                    );
                } else {
                    echo '<span class="fbc-review-message">';
                    echo 'Client ID: ' . $key . '<br/>Error: ' . $summary['msg'];
                    echo '</div>';
                }
                echo '</span>';
            }
        }
        ?>
    </span>
</span>